### PR TITLE
Add a CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by danidoni**

### CODE REVIEW

**Comment by hennevogel** [comment]
All projects here follow the openSUSE code of conduct which is https://en.opensuse.org/openSUSE:Guiding_principles

**Comment by danidoni** [comment]
> All projects here follow the openSUSE code of conduct which is https://en.opensuse.org/openSUSE:Guiding_principles

So, better if I just link to that page instead of adding the template?

**Comment by hennevogel** [comment]
> So, better if I just link to that page instead of adding the template?

For sure

**Comment by danidoni** [comment]
> > So, better if I just link to that page instead of adding the template?
> 
> For sure

Done.

**Review by hennevogel — APPROVED** [review]

**Pull request merged**
